onlineshop/customer/api/urls.py
from django.urls import path

from customer.api import views

urlpatterns = [
    path('', views.customerlist, name='customerlist'),
    path('register/', views.register, name='register'),
    path('forgetpassword/', views.forgetpassword, name='forgetpassword'),
]

onlineshop/customer/urls.py
from django.urls import path

from customer import views

app_name = 'customer'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('forgetpassword/', views.forgetpassword, name='forgetpassword'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
    path('profile/edit_passport', views.profile_edit_passport, name='profile_edit_passport'),
    path('logout/', views.auth_logout, name='logout'),

    path('fav/<int:id>/', views.booked_add, name='booked_add'),
    path('profile/orderhistory/', views.booked_animals_list, name='orderhistory'),
]

onlineshop/onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls', 'product')),
    path('admin/', admin.site.urls),
    path('api/', include('core.api.urls')),
    path('customer/', include('customer.urls', 'customer')),
    path('order/', include('order.urls', 'order'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header  =  "Animal Shelter Admin page"
admin.site.site_title  =  "Animal Shelter admin page"
admin.site.index_title  =  "Here you can manage users and orders of Animal Shelter"

onlineshop/order/urls.py
from django.urls import path

from order import views

app_name = 'order'

urlpatterns = [
    path('single_product/', views.single_product, name='single_product'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('delete_from_cart/<int:product_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('checkout/', views.checkout, name='checkout')

]

onlineshop/product/urls.py
from django.urls import path

from product import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name='home'),
]

onlineshop/customer/models.py
from django.db import models
from django.contrib.auth.models import User

from phonenumber_field.modelfields import PhoneNumberField
from account.models import Account

class Passport(models.Model):
    series_passport = models.IntegerField(blank=True,null=True)
    number_passport = models.IntegerField(blank=True,null=True)
    passport_issue = models.CharField(max_length=200,blank=True,null=True)
    date_issue = models.DateTimeField(blank=True,null=True)

class Customer(User):
    phone = PhoneNumberField(null=True, blank=True)
    address = models.TextField(max_length=400, null=True, blank=True)
    name = models.CharField(max_length=45,blank=True,null=True)
    surname = models.CharField(max_length=45,blank=True,null=True)
    patronymic = models.CharField(max_length=45, blank=True,null=True)
    date_birthday = models.DateTimeField(blank=True, null=True)
    gender = models.BooleanField(blank=True,null=True)
    passport_id = models.ForeignKey(Passport, blank=True, null=True, on_delete=models.CASCADE)


    def full_name(self):
            return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.username}"


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='customer')

onlineshop/customer/forms.py
from phonenumber_field.formfields import PhoneNumberField
from django import forms
from customer.models import Customer, Passport, User



class EditProfileForm(forms.ModelForm):
    phone = PhoneNumberField(required=False)
    address = forms.Textarea()

    class Meta:
        model = User
        # fields = ['first_name', 'last_name', 'patronymic', 'gender', 'date_birthday', 'email', 'phone', 'address']
        fields = ['first_name', 'last_name', 'email', 'phone', 'username']

# class EditProfileFormPassport(forms.ModelForm):
#
#     class Meta:
#         model = Passport
        # fields = ['series_passport', 'number_passport', 'passport_issue', 'date_issue']
        # fields = ['series_passport', 'number_passport', 'passport_issue', 'date_issue']

# class EditProfileUserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['username']

onlineshop/customer/api/views.py
from django.http import HttpResponse
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.shortcuts import get_list_or_404, render, redirect
from django.core.mail import send_mail
from django.contrib import messages

from customer.api.serializer import *


def create_customer_property_func(req):
    customer = Customer.objects.create(
        username=req.POST['username'],
        email=req.POST['email'],
        phone=req.POST['phone'],
    )
    customer.save()
    customer.set_password(req.POST['password'])
    customer.save()


@api_view(['GET', 'POST'])
def register(request):
    if request.method == 'POST':
        # print(request.POST)
        res = dict()
        if not len(request.POST['password']) > 8:
            if request.POST['password'] == request.POST['password2']:
                res['success'] = True
                res['link'] = '/customer/login'
                create_customer_property_func(request)
            else:
                res['success'] = False
        else:
            res['success'] = False
        return Response(res)


@api_view(['GET', 'POST'])
def customerlist(request):
    if request.method == 'GET':
        customer = get_list_or_404(Customer)
        serializer = CustomerSerializer(customer, many=True, context={'request': request})
        return Response(serializer.data)

    elif request.method == 'POST':
        customer = CustomerSerializer(data=request.data)
        if customer.is_valid():
            customer_instance = customer.save()
            customer_instance.set_password(customer.validated_data['password'])
            customer_instance.save()


@api_view(['GET', 'POST'])
def forgetpassword(request):
    if request.method == 'POST':
        res = dict()
        username = request.POST['username']
        try:
            customer = Customer.objects.get(username=username)
            if customer:
                his_email = customer.email
                new_password = Customer.objects.make_random_password(length=20)
                res['success'] = True
                res['link'] = '/customer/login'
                res['msg'] = f'Your new password sent to {his_email}. Please login with this'
                messages.success(request, res['msg'])
                customer.set_password(new_password)
                customer.save()
                send_mail('your new password',
                          f'your reset password is {new_password}',
                          'security@animalshelter.com',
                          [his_email],
                          fail_silently=False, )
            else:
                res['success'] = False
                res['link'] = 'customer/forgetpassword'
                res['msg'] = 'This username is not exist!'
                messages.error(request, res['msg'])
                return Response(res, status=status.HTTP_400_BAD_REQUEST)

        except:
            res['success'] = False
            res['link'] = 'customer/forgetpassword'
            res['msg'] = 'Something went wrong'
            messages.error(request, res['msg'])
            return Response(res, status=status.HTTP_400_BAD_REQUEST)

        return Response(res)
    return redirect('customer:forgetpassword')

onlineshop/customer/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect

from customer.forms import EditProfileForm
from customer.models import Customer, Passport
from product.models import Animal

from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect

# just render the related page
def login(request):
    return render(request, 'customer/login.html', {'request': request})


# just render the related page
def signup(request):
    return render(request, 'customer/signup.html', {'request': request})


# just render the related page
def forgetpassword(request):
    return render(request, 'customer/forget_password.html', {'request': request})


@login_required
def profile(request):
    if request.method == 'GET':
        this_user = Customer.objects.get(id=request.user.id)
        phone = this_user.phone
        address = this_user.address
        # print(this_user, phone, address)
        return render(request, 'customer/profile.html', {
            'request': request,
            'phone': phone,
            'address': address,
        })
    if request.method == 'POST':
        pass


@login_required
def profile_edit(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('customer:profile')
    else:
        form = EditProfileForm(instance=request.user)

    context = {
        'form': form
    }
    return render(request, 'customer/profile_edit.html', context)

@login_required
def profile_edit_passport(request):
    if request.method == 'POST':
        form = EditProfileFormPassport(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('customer:profile')
    else:
        form = EditProfileFormPassport(instance=request.user)

    context = {
        'form': form
    }
    return render(request, 'customer/profile_edit_passport.html', context)


def auth_logout(request):
    logout(request)
    return render(request, 'product/home.html', {'request': request})



@ login_required
def booked_animals_list(request):
    new = Animal.newmanager.filter(booked_by_who=request.user)
    print(new)
    return render(request,
                  'customer/orderhistory.html',
                  {'new': new})


@ login_required
def booked_add(request, id):
    animal = get_object_or_404(Animal, id=id)
    # if animal.favourites.filter(id=request.user.id).exists():
    #     animal.favourites.remove(request.user)
    # else:
    animal.favourites.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

onlineshop/customer/templates/customer/forget_password.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
    forget | Animal Shelter
{% endblock %}

{% block style %}
<style>
    #card-body {
        background-color: rgba(134, 156, 123, 0.44);
        background-color: rgba(123, 135, 156, 0.44);
    }

    #button {
        background-color: rgb(152, 138, 127);
        background-color: rgba(123, 131, 156, 0.47);
    }
</style>
{% endblock %}

{% block extra_header %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5" id="card-body">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>enter your username</b></h5>

                        <form id="form">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name='username' id="username" required>
                                <label for="username">Username</label>
                            </div>

                            <button class="btn btn-primary btn-login" id="button" type="button">
                                sent email
                            </button>

                            <hr class="my-4">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static "customer/js/forget_password.js" %}"></script>
{% endblock %}

onlineshop/customer/templates/customer/login.html
{% extends 'product/base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'customer/css/login.css' %}">
{% endblock %}

{% block title %}
    Login | Animal Shelter
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5" id="card-body">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>Login</b></h5>

                        <form action="{% url 'product:home' %}" method="post">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input type="text" class="form-control" name='username' id="username" required>
                                <label for="username">Username</label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" name="password" id="password"
                                       placeholder="Password" required>
                                <label for="password">Password</label>
                            </div>
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <div>
                                <a href="{% url "customer:forgetpassword" %}">forgot password?</a>
                            </div>
                            <div class="d-grid">
                                <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit"
                                        id="submit">
                                    log in
                                </button>
                            </div>
                            <hr class="my-4">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

onlineshop/customer/templates/customer/orderhistory.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
product | Animal Shelter
{% endblock %}

{% block left_items_in_nav %}
{% if not request.user.is_authenticated %}
<a class="btn btn-success" href="{% url 'customer:signup' %}">Signup</a>
<a class="btn btn-success" href="{% url 'customer:login' %}">Login</a>
{% else %}
<a class="btn btn-success" href="{% url 'customer:profile' %}">Profile</a>
<a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
{% endif %}
{% endblock %}

{% block main %}
<div class="card-body col-12" style="margin-top: 10px">

        <table class="table table-secondary">
            <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Animal name</th>
                <th scope="col">Specie</th>
                <th scope="col">Age</th>
                <th scope="col">Status</th>
<!--                <th scope="col">Health</th>-->
            </tr>
            </thead>
            {% for product in new %}
            <tbody>
            <tr>
                <th scope="row"><img src="/media/{{ product.photo }}" alt="{{ product.photo }}"
                                     style="max-height: 150px"></th>
                <td>{{ product.animal_name }}</td>
                <td>{{ product.specie }}</td>
                <td>{{ product.age }}</td>
                {% if product.is_given == True %}
                <td>Accepted</td>
                {% elif product.is_given == False%}
                <td>Rejected</td>
                {% else %}
                <td>In work</td>
                {% endif %}
            </tr>
            </tbody>
            {% endfor %}

        </table>
</div>


{% endblock %}

onlineshop/customer/templates/customer/profile.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
    Profile | Animal Shelter
{% endblock %}

{% block style %}
<style>
    .col-1 {
        display: contents;
        justify-content: space-around;
        margin-left: 30px;
    }
    #button {
        background-color: rgb(152, 138, 127);
        color: aliceblue;
        margin-top: 10px;
        margin-left: 10px;
    }
</style>
{% endblock %}

{% block left_items_in_nav %}
    <a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
{% endblock %}

{% block right_items_in_nav %}
    <a href={% url 'order:add_to_cart' %}>
        <span class="cart-nav">
            <img src="{% static 'product/img/cart.png' %}" style="max-height: 2.5rem" alt="cart-icon">
        </span>
    </a>
{% endblock %}

{% block main %}
    {% if request.user.is_authenticated %}
        <div class="card col-12" style="margin-top: 10px;">
            <div class="card-body">
                <p class="card-text">username: {{ request.user.username }}</p>
                {% if not request.user.first_name %}
                    <p class="card-text">First name: Not set</p>
                {% else %}
                    <p class="card-text">First name: {{ request.user.first_name }}</p>
                {% endif %}

<!--                {% if not request.user.patronymic %}-->
<!--                    <p class="card-text">patronymic: Not set</p>-->
<!--                {% else %}-->
<!--                    <p class="card-text">patronymic: {{ request.user.patronymic }}</p>-->
<!--                {% endif %}-->



                {% if not request.user.last_name %}
                    <p class="card-text">Surname: Not set</p>
                {% else %}
                    <p class="card-text">Surname: {{ request.user.last_name }}</p>
                {% endif %}
<!--                <p class="card-text">DATE_BIRTHDAY: {{ request.customer.date_birthday }}</p>-->
<!--                <p class="card-text">GENDER: {{ request.customer.gender }}</p>-->
<!--                {% if not address %}-->
<!--                    <p class="card-text">address: Not set</p>-->
<!--                {% else %}-->
<!--                    <p class="card-text">address: {{ request.user.address }}</p>-->
<!--                {% endif %}-->
                <p class="card-text">email: {{ request.user.email }}</p>
                <p class="card-text">phone: {{ phone }}</p>
<!--                <p>Passport information:</p>-->
<!--                <p class="card-text">SERIES_PASSPORT: {{ request.passport.series_passport }}</p>-->
<!--                <p class="card-text">number_passport: {{ request.passport.number_passport }}</p>-->
<!--                <p class="card-text">date_issue: {{ request.passport.date_issue }}</p>-->
<!--                <p class="card-text">passport_issue: {{ request.passport.passport_issue }}</p>-->
            </div>
        </div>
        <div class="col-1">
            <a class="btn" id="button" href="{% url "customer:profile_edit" %}">edit</a>
            <a class="btn" id="button" href="{% url "customer:orderhistory" %}">Order history</a>
            <!--            <a class="btn" id="button" href="{% url "customer:profile_edit_passport" %}">edit passport</a>-->
        </div>
    {% endif %}

{% endblock %}

<!--{% block status %}-->
<!--    {% if request.user.is_authenticated %}-->
<!--        <div class="card col-12" style="margin-top: 10px;">-->
<!--            <div class="card-body">-->
<!--                <p class="card-text">number: {{ request.Customer.objects }}-->
<!--                </p>-->
<!--                <p class="card-text">email: {{ request.user.email }}</p>-->
<!--                <p class="card-text">phone: {{ phone }}</p>-->

<!--            </div>-->
<!--        </div>-->
<!--    {% endif %}-->

<!--{% endblock %}-->

onlineshop/customer/templates/customer/profile_edit.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
    Profile | Animal Shelter
{% endblock %}

{% block style %}
    <style>
        #button {
            background-color: rgb(152, 138, 127);
        }
    </style>
{% endblock %}

{% block left_items_in_nav %}
    <a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
{% endblock %}

{% block main %}
    <div class="container">
        <div class="row">
            <div class="col-12" id="card-container">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5" id="card-body">
                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>edit your profile</b></h5>
                        <div class="form-group">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button class="btn btn-primary btn-login text-uppercase fw-bold" id="button"
                                        type="submit">
                                    Update
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<!--{% block status %}-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-12" id="card-container">-->
<!--                <div class="card border-0 shadow rounded-3 my-5">-->
<!--                    <div class="card-body p-4 p-sm-5" id="card-body">-->
<!--                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>edit your profile</b></h5>-->
<!--                        <div class="form-group">-->
<!--                            <form method="POST">-->
<!--                                {% csrf_token %}-->
<!--                                {{ form.as_p }}-->
<!--                                <button class="btn btn-primary btn-login text-uppercase fw-bold" id="button"-->
<!--                                        type="submit">-->
<!--                                    Update-->
<!--                                </button>-->
<!--                            </form>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--{% endblock %}-->

onlineshop/customer/templates/customer/profile_edit_passport.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
    Profile | Animal Shelter
{% endblock %}

{% block style %}
    <style>
        #button {
            background-color: rgb(152, 138, 127);
        }
    </style>
{% endblock %}

{% block left_items_in_nav %}
    <a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
{% endblock %}

<!--{% block main %}-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-12" id="card-container">-->
<!--                <div class="card border-0 shadow rounded-3 my-5">-->
<!--                    <div class="card-body p-4 p-sm-5" id="card-body">-->
<!--                        <h5 class="card-title text-center mb-5 fw-light fs-5"><b>edit your profile</b></h5>-->
<!--                        <div class="form-group">-->
<!--                            <form method="POST">-->
<!--                                {% csrf_token %}-->
<!--                                {{ form.as_p }}-->
<!--                                <button class="btn btn-primary btn-login text-uppercase fw-bold" id="button"-->
<!--                                        type="submit">-->
<!--                                    Update-->
<!--                                </button>-->
<!--                            </form>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--{% endblock %}-->

onlineshop/customer/templates/customer/signup.html
{% extends 'product/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'customer/css/signup.css' %}">
{% endblock %}

{% block title %}
Signup | Animal Shelter
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" id="card-container">
            <div class="card border-0 shadow rounded-3 my-5">
                <div class="card-body p-4 p-sm-5" id="card-body">
                    <h5 class="card-title text-center mb-5 fw-light fs-5"><b>Sign up</b></h5>
                    <form id="form">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="username" id="username"
                                   placeholder="Username" required>

                            <label for="username">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" name="email" id="email" placeholder="email">

                            <label for="email">Email</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="phone" id="phone" placeholder="phone">

                            <label for="phone">Phone</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" name="password" id="password"
                                   placeholder="Password" required>
                            <label for="password">Password</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" name="password2" id="password2"
                                   placeholder="Password Confirmation" required>
                            <label for="password2">Password Confirmation</label>
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-primary btn-login text-uppercase fw-bold" id="button" type="button">
                                Sign Up
                            </button>
                        </div>
                        <hr class="my-4">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'customer/js/register.js' %}"></script>
{% endblock %}