onlineshop/customer/urls.py
from django.urls import path

from customer import views

app_name = 'customer'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('forgetpassword/', views.forgetpassword, name='forgetpassword'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
    path('profile/edit_passport', views.profile_edit_passport, name='profile_edit_passport'),
    path('logout/', views.auth_logout, name='logout'),

    path('fav/<int:id>/', views.booked_add, name='booked_add'),
    path('profile/orderhistory/', views.booked_animals_list, name='orderhistory'),
]

onlineshop/onlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls', 'product')),
    path('admin/', admin.site.urls),
    path('api/', include('core.api.urls')),
    path('customer/', include('customer.urls', 'customer')),
    path('order/', include('order.urls', 'order'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header  =  "Animal Shelter Admin page"
admin.site.site_title  =  "Animal Shelter admin page"
admin.site.index_title  =  "Here you can manage users and orders of Animal Shelter"

onlineshop/order/urls.py
from django.urls import path

from order import views

app_name = 'order'

urlpatterns = [
    path('single_product/', views.single_product, name='single_product'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('delete_from_cart/<int:product_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('checkout/', views.checkout, name='checkout')

]

onlineshop/product/api/urls.py
from django.urls import path

from product.api import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductAPIView.as_view()),
    path('<str:category>/', views.ProductAPIView.as_view()),
]

onlineshop/product/urls.py
from django.urls import path

from product import views

app_name = 'product'

urlpatterns = [
    path('', views.home, name='home'),
]

onlineshop/product/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone
from django.urls import reverse


class Location(models.Model):
    location_name = models.CharField(max_length=64, null=False)
    location_description = models.CharField(max_length=64, null=False)

class Health_description(models.Model):
    health_level = models.IntegerField(null=False)
    health_description = models.CharField(max_length=64, null=False)


class Animal(models.Model):
    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter()

    animal_name = models.CharField(max_length=64, null=False)
    specie = models.CharField(max_length=32, null=False)
    age = models.SmallIntegerField(null=False)
    gender = models.CharField(max_length=32, null=False)
    health = models.IntegerField(null=False)
    location = models.ForeignKey(Location, null=False, on_delete=models.CASCADE)
    appearance_date = models.DateTimeField(null=False)
    photo = models.ImageField(upload_to='product_image', null=True, blank=True)
    is_given = models.BooleanField(blank=True, null=True, default=None)
    booked_by_who = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)

    objects = models.Manager()  # default manager
    newmanager = NewManager()  # custom manager

    # def __str__(self):
    #     return self.createdAt
    def __str__(self):
        return self.animal_name

onlineshop/product/api/views.py
from django.shortcuts import get_list_or_404, get_object_or_404
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.views import APIView

from product.api.serializer import ProductsListSerializer
from product.models import Animal


class ProductAPIView(APIView):
    serializer = ProductsListSerializer

    def get_queryset(self):
        return Animal.objects.all()

    def get(self, request, category=None):
        if category:
            queryset = get_list_or_404(Animal, category__category_name=category)
        else:
            queryset = self.get_queryset()

        serializer = ProductsListSerializer(queryset, context={'request': request}, many=True)
        return Response(serializer.data)

onlineshop/product/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_list_or_404
from django.contrib import messages

from product.models import Animal


def home(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return render(request, 'product/home.html', {'request': request})
        else:
            message = 'username or password is not correct!'
            messages.error(request, message)
            return redirect('customer:login')

    return render(request, 'product/home.html', {'request': request})

onlineshop/product/templates/product/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static '/product/css/base.css' %}">

    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="main-container">
    <div class="header">

        <nav class="navbar navbar-fixed-top">

            <div class="left_items_in_nav">
                <div class="container">
                    <a href="{% url 'product:home' %}" type="button" class="btn navs-button btn-success">Home</a>
                    {% block left_items_in_nav %}{% endblock %}
                </div>
            </div>

            <div class="right-items-in-nav">
                <div class="container">
                    {% block right_items_in_nav %}{% endblock %}
                </div>
            </div>
        </nav>
        {% block extra_header %}{% endblock %}
    </div>

    <div class="container outer-main">
        <div class="cont row main-component">
            {% block main %}{% endblock %}
        </div>
        <div class="cont2 row main-component">
            {% block status %}{% endblock %}
        </div>
    </div>

    <div class="container-fluid footer" id="footer">
        <p></p>
        {% block extra_footer %}{% endblock %}
    </div>
</div>

{% block js %}{% endblock %}
</body>
</html>

onlineshop/product/templates/product/home.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}HOME | Animal Shelter{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static '/product/css/home.css' %}">
{% endblock %}

{% block left_items_in_nav %}
    {% if not request.user.is_authenticated %}
        <a class="btn btn-success" href="{% url 'customer:signup' %}">Signup</a>
        <a class="btn btn-success" href="{% url 'customer:login' %}">Login</a>
    {% else %}
        <a class="btn btn-success" href="{% url 'customer:profile' %}">Profile</a>
        <a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
    {% endif %}
{% endblock %}

{% block right_items_in_nav %}
    <a href={% url 'order:cart' %}>
        <span class="cart-nav">
            <img src="{% static 'product/img/cart.png' %}" style="max-height: 2.5rem" alt="cart-icon">
        </span>
    </a>
    <div class="search-bar">
        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-success my-2 my-sm-0" type="submit" id="search-btn">Search</button>
    </div>
{% endblock %}

{% block extra_header %}
    <section class="section category">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" style="text-align: center">Welcome to our Animal Shelter! </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto"></ul>
            </div>
        </nav>
    </section>
{% endblock %}

{% block main %}
    <section>
        <div class="container product-container">
            <div class="card-group">
                <div class="row"></div>
            </div>
        </div>
    </section>
{% endblock %}

{#{% block main_right %}#}
{#    <div class="container right-component">#}
{##}
{#    </div>#}
{#{% endblock %}#}

{% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!--    <script src="{% static 'product/js/categories_nav.js' %}"></script>-->
    <script src={% static 'product/js/products.js' %}></script>
{% endblock %}

onlineshop/product/templates/product/single_product.html
{% extends 'product/base.html' %}
{% load static %}

{% block title %}
    product | Animal Shelter
{% endblock %}

{% block left_items_in_nav %}
    {% if not request.user.is_authenticated %}
        <a class="btn btn-success" href="{% url 'customer:signup' %}">Signup</a>
        <a class="btn btn-success" href="{% url 'customer:login' %}">Login</a>
    {% else %}
        <a class="btn btn-success" href="{% url 'customer:profile' %}">Profile</a>
        <a class="btn btn-success" href="{% url 'customer:logout' %}">Logout</a>
    {% endif %}
{% endblock %}

{% block main %}
    <div class="card-body col-12" style="margin-top: 10px">
        <form method="POST" action="{% url 'order:add_to_cart' %}">

            <table class="table table-secondary">
                <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Animal name</th>
                    <th scope="col">Specie</th>
                    <th scope="col">Age</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Health</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row"><img src="/media/{{ product.photo }}" alt="{{ product.photo }}"
                                         style="max-height: 150px"></th>
                    <td>{{ product.animal_name }}</td>
                    <td>{{ product.specie }}</td>
                    <td>{{ product.age }}</td>
                    <td>{{ product.gender }}</td>
                    <td>{{ product.health }}</td>
                </tr>
                </tbody>

            </table>
            <div class="col-2">
                <input type="hidden" name="product_id" value={{ product.id }}>
                <button type="submit" class="btn btn-success">add to cart</button>
            </div>
        </form>
    </div>


{% endblock %}